spring:
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
            ddl-auto: none
        properties:
            hibernate:
                show_sql: false
                format_sql: false
                highlight_sql: false
        defer-datasource-initialization: true

    sql:
        init:
            mode: never

    data:
        web:
            pageable:
                one-indexed-parameters: true
        redis:
            host: ENC(NlaOnFEohOhLwfm3BQKYzQxJYtI72xNO)
            port: 6379
            password: ENC(cAV37F+FL3IUpEFNaq367sJN+c36j4oB)


    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        username: ENC(bGvDWXdgAsFNCvvwrW9+eQ==)
        password: ENC(yb9c5bnqFBYAoXvuBddv6A==)
        url: ENC(VDulTKVcDKlyXOvmiK5/diPARDSH31SjTdWYIFrdcRrKKCExvC2x5jPireljXeSYkULO1V5zzEW+/0RrGu8tJlrRo9ZxvcXlIyrGMCttEZKYy501NI12s23HuzL3xCyU0uZzFFicleA=)

    mvc:
        path match:
            matching-strategy: ant_path_matcher

    security:
        oauth2:
            client:
                registration:
                    naver:
                        client-id: ENC(WhoPNzSBk87tCRMJSNPc8HSb3eu+PtXdyr2PhpUkN5c=)
                        client-secret: ENC(iT358x0GiqKIcpMF8KEwhj+gxdIeU04F)
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        redirect-uri: "https://j10d202.p.ssafy.io/login/oauth2/code/naver"
                        client-name: Naver

                    kakao:
                        client-id: ENC(ZKoCVID7ulkNpvmbGVPMu+Ma8tXC3okS7gYFjDJLR7O67U2KitHYYQF63hQDErHI)
                        client-secret: ENC(aR160x70en30H3kkqxCxc+pIvX7OLXxri+GrFYgc9Tz6cDmcAEOciJ9HgveOgaWB)
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
                        #                        redirect-uri: "https://j10d202.p.ssafy.io/login/oauth2/code/kakao"
                        redirect-uri: "https://j10d202.p.ssafy.io/{action}/oauth2/code/{registrationId}"

                        client-name: Kakao

                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-info-authentication-method: header
                        user-name-attribute: response # Naver 응답 값 resultCode,message, response 중 response 지정

                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-info-authentication-method: header
                        user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

jasypt:
    key: ${JASYPT_KEY}

jwt:
    secret: ENC(8bL40g574ZUX0POwuNMfP6P/q+pwKcMrJRktF3mOetHNovtdUcYS9zbDAswxsVs5C67EJXjp55hjtv2NDMRTw6EUAdTJ2eO3/wQvit4WSsalh556Kc+n+0PLas8KTi3vEDfp2VB1PN+qTr8rr2p4kg==)

